language: go
go: 1.11.x
branches:
  only:
    - shannon-go1.12.5

install: true

before_script:
  - pwd
  - which go
  - echo $GOPATH

script:
  - cd src
  - rm -rf ./bin ./pkg
  - ./make.bash

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
